spring:
  application:
    name: gateway
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false
        hbm2ddl:
          auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/currency_gateway
    username: postgres
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: ${RABBITMQ_PASSWORD}
  data:
    redis:
      port: 6379
      host: localhost
  cache:
    type: redis
    redis:
      time-to-live: 300000

app:
  rabbitmq:
    exchange: request.exchange

rates-collector:
  interval: 300000

fixer:
  api:
    key: ${FIXER_API_KEY}

logging:
  level:
    com.example.gateway.client.FixerClient: DEBUG
    com.example.gateway.scheduler.RatesCollectorScheduler: DEBUG
    com.example.gateway.service.impl.CurrencyRateServiceImpl: DEBUG
    com.example.gateway.service.impl.RequestStatServiceImpl: DEBUG